language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "$LICENSES_HASH" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "$LICENSES_HASH_TWO" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools

install: ./gradlew build --stacktrace

script:
  - ./gradlew check --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: OgyW2LfEW4Ibq06kYzN10Bo2CQe5CUFv5VUoZlBSU+cIEjBWBXRBF4p4tR4eH+ZYSWbYPDHGVQhEgUY834D6yQ6zubo7QR+aZmy1x+hv/RAz6rvrjVwq9z+GgWgf5aK0qxHYyUqrgZggq0NF4bsTN5m21RJzRb/poUcVt5J+ytXhwyoa4hBmii4vjrAiUMlcp3SrWmqNrDIF6iTXiLWdZ5HB9jik/yngUjuJi5W5rbm6B4X49eUF7+V0mqso6O3/ax9S3FCibWSHmQxF95vrcgcd8v1hqYKN3/IGfVXOC9cqRY2ALOOGw4Vg5rL5Lip+YPm/8Se3LpwyKrxQ6wssq7yXrrwI4pGo9Yy3OzrNencZ8zKTs0P3ZYOuu9Fg0G8BpZUVIBe/WUIJItAlTjg0AiDB/KMpfVPXxuqGuXkCw190NzV2vMpBSnSUrvJnKrRGdbdWyDWMZWpoHjwisCPT+bJjlGn1n6sB7oM9ErMaXQNLmpZHj6ksQ0DT6xAgd8/xoZaYSs+jcaWD8AQ/5H61lLEBSg3oGoYXF9w+KnIferONowWUgmko1vGu4pqW40/EJs5ewex41Y3widzsdmOMqz37+Ooe9JKN/5J/QKmafwxm6VDnhoPWi2mUS81fh8kru4bgDAHcbXgWkuUSmf/DFKPbLSzjn0nda2U4v9s9TVM=
  - secure: D8lMrIYZPRiSnAyMS9zUUiEFh3bVglbB17aZ6j7jLN0AGnvLBLr5REXsD/rKd6zadsXNfZ5r3V02cPto0OKsXfRGviGb5F0GvRxTV/454IOuBHHqoynvh1LtyV8lILLBxWtt/834d0asi/FDKQP20kICEj0mjXr3iz7cSGPMGhl2slKVr9NAdxDaLAP8HWfJiaiMDwajrfrj6S5MZrxS4moa8k6pIwwUADeUSQ2yfUDPIM2G7hh/DrED9fdG5TiQCUM3p/9VtveWdW66eXxOi1+BxIjjiW7PxTJs820xISZ0q+Khy6RUoP/RaJeTdG9Ou9qWgaXGb/jxxr/FH91KR/AfEIjH9E5W5S6Bp8oxh0Ycl/mWnLaLag1sl5+zjQry3DQyQ/kfdwUzhfNeVjmW+txLKADg8T1IzrZS0wNw5grkGUXMPAv+yBIGEHcOIOCEEYsdOvSRy5ftAn6Ls0It5S8lf0MqmnPH3GaEJcwGIynbovPoOy6ga8mqO4y2m6SfYN17o6EJ3TpPlL9UeQdJnhXi2iJXxNcnFxhHdiln1xF1OBxugb2UWeLdM+NCN/QdB/5ej3KPQeCQ8oGi0itJu0LT7tNVnLKIwa9/C/8obZvSEQrzXfOpdb7cqw+Re8nao5wxDy22RSMWfN9naKGkDmYJ8cQBQBKskUlnv8IGKFY=

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
